################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
httpcli.obj: C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/httpcli.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me -Ooff --include_path="C:/ti/CCS6.2/xdctools_3_32_01_22_core/packages" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/kernel/tirtos/packages/ti/sysbios/posix" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/kernel/tirtos/packages/" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS/include" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/client/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/common/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/platform/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/drivers/net/wifi/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/drivers/net/wifi/source/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/devices/cc32xx/driverlib/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/devices/cc32xx/inc/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client" --define=__SL__ --define=HTTPCli_LIBTYPE_MIN --define=__CCS__ --define=cc3200 --define=ccs --define=USE_CC3220_ROM_DRV_API --define=SL_PLATFORM_MULTI_THREADED --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="httpcli.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

httpstr.obj: C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/httpstr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me -Ooff --include_path="C:/ti/CCS6.2/xdctools_3_32_01_22_core/packages" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/kernel/tirtos/packages/ti/sysbios/posix" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/kernel/tirtos/packages/" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS/include" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/client/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/common/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/platform/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/drivers/net/wifi/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/drivers/net/wifi/source/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/devices/cc32xx/driverlib/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/devices/cc32xx/inc/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client" --define=__SL__ --define=HTTPCli_LIBTYPE_MIN --define=__CCS__ --define=cc3200 --define=ccs --define=USE_CC3220_ROM_DRV_API --define=SL_PLATFORM_MULTI_THREADED --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="httpstr.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

lookup.obj: C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/lookup.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me -Ooff --include_path="C:/ti/CCS6.2/xdctools_3_32_01_22_core/packages" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/kernel/tirtos/packages/ti/sysbios/posix" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/kernel/tirtos/packages/" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS/include" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/client/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/common/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/platform/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/drivers/net/wifi/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/drivers/net/wifi/source/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/devices/cc32xx/driverlib/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/devices/cc32xx/inc/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client" --define=__SL__ --define=HTTPCli_LIBTYPE_MIN --define=__CCS__ --define=cc3200 --define=ccs --define=USE_CC3220_ROM_DRV_API --define=SL_PLATFORM_MULTI_THREADED --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lookup.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ssock.obj: C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/ssock.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me -Ooff --include_path="C:/ti/CCS6.2/xdctools_3_32_01_22_core/packages" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/kernel/tirtos/packages/ti/sysbios/posix" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/kernel/tirtos/packages/" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS/include" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/client/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/common/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client/platform/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/drivers/net/wifi/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/drivers/net/wifi/source/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/devices/cc32xx/driverlib/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/devices/cc32xx/inc/" --include_path="C:/ti/simplelink_cc32xx_sdk_1_40_02_01_eng/source/ti/net/http/client" --define=__SL__ --define=HTTPCli_LIBTYPE_MIN --define=__CCS__ --define=cc3200 --define=ccs --define=USE_CC3220_ROM_DRV_API --define=SL_PLATFORM_MULTI_THREADED --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ssock.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


